const Types = {
  LOGIN: "LOGIN",
  SUBMIT_REGISTER_USER_FORM: "SUBMIT_REGISTER_USER_FORM",
  REGISTER_USER_PENDING: "REGISTER_USER_PENDING",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE"
};

export default Types;