const forumConstants = {
  ADD_PARENT_PENDING: "ADD_PARENT_PENDING",
  ADD_PARENT_SUCCESS: "ADD_PARENT_SUCCESS",
  ADD_PARENT_FAILURE: "ADD_PARENT_FAILURE",
  ADD_CHILD_PENDING: "ADD_CHILD_PENDING",
  ADD_CHILD_SUCCESS: "ADD_CHILD_SUCCESS",
  ADD_CHILD_FAILURE: "ADD_CHILD_FAILURE",
  GET_COMMENTS_PENDING: "GET_COMMENTS_PENDING",
  GET_COMMENTS_SUCCESS: "GET_COMMENTS_SUCCESS",
  GET_COMMENTS_FAILURE: "GET_COMMENTS_FAILURE",
};

export default forumConstants;
