const investmentConstants = {
  CREATE_STOCK_PENDING: "CREATE_STOCK_PENDING",
  CREATE_STOCK_SUCCESS: "CREATE_STOCK_SUCCESS",
  CREATE_STOCK_FAILURE: "CREATE_STOCK_FAILURE",
  GET_STOCKS_PENDING: "GET_STOCKS_PENDING",
  GET_STOCKS_SUCCESS: "GET_STOCKS_SUCCESS",
  GET_STOCKS_FAILURE: "GET_STOCKS_FAILURE",
  DELETE_STOCK_PENDING: "DELETE_STOCK_PENDING",
  DELETE_STOCK_SUCCESS: "DELETE_STOCK_SUCCESS",
  DELETE_STOCK_FAILURE: "DELETE_STOCK_FAILURE",
};

export default investmentConstants;
