const newsConstants = {
  NEWS_PENDING: "NEWS_PENDING",
  NEWS_SUCCESS: "NEWS_SUCCESS",
  NEWS_FAILURE: "NEWS_FAILURE",
  STOCK_NEWS_PENDING: "STOCK_NEWS_PENDING",
  STOCK_NEWS_SUCCESS: "STOCK_NEWS_SUCCESS",
  STOCK_NEWS_FAILURE: "STOCK_NEWS_FAILURE",
};

export default newsConstants;
