const noteConstants = {
  GET_USER_NOTES_PENDING: "GET_USER_NOTES_PENDING",
  GET_USER_NOTES_SUCCESS: "GET_USER_NOTES_SUCCESS",
  GET_USER_NOTES_FAILURE: "GET_USER_NOTES_FAILURE",
  GET_RELEVANT_NOTES_PENDING: "GET_RELEVANT_NOTES_PENDING",
  GET_RELEVANT_NOTES_SUCCESS: "GET_RELEVANT_NOTES_SUCCESS",
  GET_RELEVANT_NOTES_FAILURE: "GET_RELEVANT_NOTES_FAILURE",
  CREATE_NOTE_PENDING: "CREATE_NOTE_PENDING",
  CREATE_NOTE_SUCCESS: "CREATE_NOTE_SUCCESS",
  CREATE_NOTE_FAILURE: "CREATE_NOTE_FAILURE",
  EDIT_NOTE_PENDING: "EDIT_NOTE_PENDING",
  EDIT_NOTE_SUCCESS: "EDIT_NOTE_SUCCESS",
  EDIT_NOTE_FAILURE: "EDIT_NOTE_FAILURE",
  DELETE_NOTE_PENDING: "DELETE_NOTE_PENDING",
  DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
  DELETE_NOTE_FAILURE: "DELETE_NOTE_FAILURE",
  TOGGLE_NOTELIST: "TOGGLE_NOTELIST",
};

export default noteConstants;