const portfolioConstants = {
  CREATE_PORTFOLIO_PENDING: "CREATE_PORTFOLIO_PENDING",
  CREATE_PORTFOLIO_SUCCESS: "CREATE_PORTFOLIO_SUCCESS",
  CREATE_PORTFOLIO_FAILURE: "CREATE_PORTFOLIO_FAILURE",
  GET_PORTFOLIOS_PENDING: "GET_PORTFOLIOS_PENDING",
  GET_PORTFOLIOS_SUCCESS: "GET_PORTFOLIOS_SUCCESS",
  GET_PORTFOLIOS_FAILURE: "GET_PORTFOLIOS_FAILURE",
  DELETE_PORTFOLIO_PENDING: "DELETE_PORTFOLIO_PENDING",
  DELETE_PORTFOLIO_SUCCESS: "DELETE_PORTFOLIO_SUCCESS",
  DELETE_PORTFOLIO_FAILURE: "DELETE_PORTFOLIO_FAILURE",
  EDIT_PORTFOLIO_PENDING: "EDIT_PORTFOLIO_PENDING",
  EDIT_PORTFOLIO_SUCCESS: "EDIT_PORTFOLIO_SUCCESS",
  EDIT_PORTFOLIO_FAILURE: "EDIT_PORTFOLIO_FAILURE",
};

export default portfolioConstants;
