const portfolioConstants = {
  CREATE_PORTFOLIO_REQUEST: "CREATE_PORTFOLIO_REQUEST",
  CREATE_PORTFOLIO_SUCCESS: "CREATE_PORTFOLIO_SUCCESS",
  CREATE_PORTFOLIO_FAILURE: "CREATE_PORTFOLIO_FAILURE",
  CREATE_PORTFOLIO_PENDING: "CREATE_PORTFOLIO_PENDING",
};

export default portfolioConstants;
