const portfolioConstants = {
  SUBMIT_CREATE_PORTFOLIO_FORM: "SUBMIT_CREATE_PORTFOLIO_FORM",
  CREATE_PORTFOLIO_SUCCESS: "CREATE_PORTFOLIO_SUCCESS",
  CREATE_PORTFOLIO_FAILURE: "CREATE_PORTFOLIO_FAILURE",
  CREATE_PORTFOLIO_PENDING: "CREATE_PORTFOLIO_PENDING",
};

export default portfolioConstants;
