const screenerConstants = {
  SAVE_SCREENER_PENDING: "SAVE_SCREENER_PENDING",
  SAVE_SCREENER_SUCCESS: "SAVE_SCREENER_SUCCESS",
  SAVE_SCREENER_FAILURE: "SAVE_SCREENER_FAILURE",
  GET_SCREENER_RESULTS_PENDING: "GET_SCREENER_RESULTS_PENDING",
  GET_SCREENER_RESULTS_SUCCESS: "GET_SCREENER_RESULTS_SUCCESS",
  GET_SCREENER_RESULTS_FAILURE: "GET_SCREENER_RESULTS_FAILURE",
  LOAD_SCREENERS_PENDING: "LOAD_SCREENERS_PENDING",
  LOAD_SCREENERS_SUCCESS: "LOAD_SCREENERS_SUCCESS",
  LOAD_SCREENERS_FAILURE: "LOAD_SCREENERS_FAILURE",
  DELETE_SCREENER_PENDING: "DELETE_SCREENER_PENDING",
  DELETE_SCREENER_SUCCESS: "DELETE_SCREENER_SUCCESS",
  DELETE_SCREENER_FAILURE: "DELETE_SCREENER_FAILURE",
  SAVE_PARAMS_PENDING: "SAVE_PARAMS_PENDING",
  SAVE_PARAMS_SUCCESS: "SAVE_PARAMS_SUCCESS",
  SAVE_PARAMS_FAILURE: "SAVE_PARAMS_FAILURE", 
}

export default screenerConstants;
