const stockConstants = {
  SUBMIT_CREATE_STOCK_FORM: "SUBMIT_CREATE_STOCK_FORM",
  CREATE_STOCK_SUCCESS: "CREATE_STOCK_SUCCESS",
  CREATE_STOCK_FAILURE: "CREATE_STOCK_FAILURE",
  CREATE_STOCK_PENDING: "CREATE_STOCK_PENDING",
};

export default stockConstants;
