const stockConstants = {
  GET_STOCK_BASIC_PENDING: "GET_STOCK_BASIC_PENDING",
  GET_STOCK_BASIC_SUCCESS: "GET_STOCK_BASIC_SUCCESS",
  GET_STOCK_BASIC_FAILURE: "GET_STOCK_BASIC_FAILURE",
  GET_STOCK_INCOME_PENDING: "GET_STOCK_INCOME_PENDING",
  GET_STOCK_INCOME_SUCCESS: "GET_STOCK_INCOME_SUCCESS",
  GET_STOCK_INCOME_FAILURE: "GET_STOCK_INCOME_FAILURE",
  GET_STOCK_BALANCE_PENDING: "GET_STOCK_BALANCE_PENDING",
  GET_STOCK_BALANCE_SUCCESS: "GET_STOCK_BALANCE_SUCCESS",
  GET_STOCK_BALANCE_FAILURE: "GET_STOCK_BALANCE_FAILURE",
  GET_STOCK_CASHFLOW_PENDING: "GET_STOCK_CASHFLOW_PENDING",
  GET_STOCK_CASHFLOW_SUCCESS: "GET_STOCK_CASHFLOW_SUCCESS",
  GET_STOCK_CASHFLOW_FAILURE: "GET_STOCK_CASHFLOW_FAILURE",
  GET_PREDICTION_DAILY_PENDING: "GET_PREDICTION_DAILY_PENDING",
  GET_PREDICTION_DAILY_SUCCESS: "GET_PREDICTION_DAILY_SUCCESS",
  GET_PREDICTION_DAILY_FAILURE: "GET_PREDICTION_DAILY_FAILURE",
  GET_PAPER_TRADING_PENDING: "GET_PAPER_TRADING_PENDING",
  GET_PAPER_TRADING_SUCCESS: "GET_PAPER_TRADING_SUCCESS",
  GET_PAPER_TRADING_FAILURE: "GET_PAPER_TRADING_FAILURE",
};

  export default stockConstants;
