const trendConstants = {
  TRENDING_INVESTMENTS_PENDING: "TRENDING_INVESTMENTS_PENDING",
  TRENDING_INVESTMENTS_SUCCESS: "TRENDING_INVESTMENTS_SUCCESS",
  TRENDING_INVESTMENTS_FAILURE: "TRENDING_INVESTMENTS_FAILURE",
};

export default trendConstants;