const userConstants = {
  REGISTER_PENDING: "REGISTER_PENDING",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",
  LOGIN_PENDING: "LOGIN_PENDING",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  GET_USERNAME_PENDING: "GET_USERNAME_PENDING",
  GET_USERNAME_SUCCESS: "GET_USERNAME_SUCCESS",
  GET_USERNAME_FAILURE: "GET_USERNAME_FAILURE",
};

export default userConstants;
