const watchlistConstants = {
  GET_WATCHLISTS_PENDING: "GET_WATCHLISTS_PENDING",
  GET_WATCHLISTS_SUCCESS: "GET_WATCHLISTS_SUCCESS",
  GET_WATCHLISTS_FAILURE: "GET_WATCHLISTS_FAILURE",
  GET_FOLLOWING_PENDING: "GET_FOLLOWING_PENDING",
  GET_FOLLOWING_SUCCESS: "GET_FOLLOWING_SUCCESS",
  GET_FOLLOWING_FAILURE: "GET_FOLLOWING_FAILURE",
  ADD_FOLLOWING_PENDING: "ADD_FOLLOWING_PENDING",
  ADD_FOLLOWING_SUCCESS: "ADD_FOLLOWING_SUCCESS",
  ADD_FOLLOWING_FAILURE: "ADD_FOLLOWING_FAILURE",
  DELETE_FOLLOWING_PENDING: "DELETE_FOLLOWING_PENDING",
  DELETE_FOLLOWING_SUCCESS: "DELETE_FOLLOWING_SUCCESS",
  DELETE_FOLLOWING_FAILURE: "DELETE_FOLLOWING_FAILURE",
};

export default watchlistConstants;
