CREATE TABLE IF NOT EXISTS BalanceSheets (
    stock_ticker VARCHAR(10) PRIMARY KEY,
    fiscal_date_ending DATE PRIMARY KEY,
    cash_and_short_term_investments INTEGER(20),
    current_net_receivables INTEGER(20),
    inventory INTEGER(20),
    other_current_assets INTEGER(20),
    property_plant_equipment INTEGER(20),
    goodwill INTEGER(20),
    intangible_assets INTEGER(20),
    long_term_investments INTEGER(20),
    other_non_current_assets INTEGER(20),
    current_accounts_payable INTEGER(20),
    short_term_debt INTEGER(20),
    other_current_liabilities INTEGER(20),
    long_term_debt INTEGER(20),
    other_non_current_liabilities INTEGER(20),
    retained_earnings INTEGER(20),
    total_shareholder_equity INTEGER(20),
    -- PRIMARY KEY (stock_ticker, fiscal_date_ending)
);
