models:
    lstm_vanilla:
        name: "Default LSTM"
        type: "tf-keras"
        save_filename: "lstm_tanh_200e_1step.h5"

        training:
            train_test_split: 0.80
            epochs: 200
            batch_size: 4
            n_features: 1
            n_steps: 60

    lstm_cnn:
        name: "CNN-LSTM"
        type: "tf-keras"
        save_filename: "cnn_lstm.h5"

        training:
            train_test_split: 0.80
            epochs: 200
            batch_size: 4
            n_features: 1
            n_steps: 60
            n_seq: 6
            n_steps_cnn: 10

train_data:
    filename: "IBM_daily_adjusted.json"
    sequence_length: 5580
    normalise: true
    columns_to_use: ["5. adjusted close"]

prediction_modes:
    walk_forward:
        name: "Walk-Forward (Vanilla LSTM)"
        length: 60
    multistep_series:
        name: "Series (Vanilla LSTM)"
        length: 120
    cnn:
        name: "Walk-Forward (CNN-LSTM)"
        length: 60
